@WebApiPlayground_HostAddress = http://localhost:5024

GET {{WebApiPlayground_HostAddress}}/numbers
Accept: application/json

###

GET {{WebApiPlayground_HostAddress}}/numbers/five
Accept: application/json

###